/**
 * Generate CRUD Command
 *
 * Generates CRUD route files for a model using the CRUD Generator.
 */

import { Command } from 'commander';
import * as fs from 'fs/promises';
import * as path from 'path';
import { success, info, error as logError } from '../../utils/logger.js';
import { CLIError, wrapCommand } from '../../utils/error-handler.js';

/**
 * CRUD generation options
 */
interface GenerateCRUDOptions {
  output?: string;
  basePath?: string;
  softDelete?: boolean;
  pagination?: boolean;
  filtering?: boolean;
  sorting?: boolean;
  search?: boolean;
  relationships?: boolean;
}

/**
 * Generate route file content for CRUD endpoints
 */
function generateCRUDRouteContent(modelName: string, options: GenerateCRUDOptions): string {
  const basePath = options.basePath || `/${modelName.toLowerCase()}s`;
  const lines: string[] = [];

  // Imports
  lines.push(`import type { RequestContext, NextFunction } from '@web-loom/api-core';`);
  lines.push(`import { CRUDGenerator } from '@web-loom/api-generator-crud';`);
  lines.push(`import { ${modelName} } from '../models/${modelName.toLowerCase()}.js';`);
  lines.push(
    `import { database } from '../database.js'; // You'll need to export your database adapter`
  );
  lines.push(``);

  // Create CRUD generator instance
  lines.push(`/**`);
  lines.push(` * CRUD Generator for ${modelName}`);
  lines.push(` * `);
  lines.push(` * Generated by Web Loom CLI`);
  lines.push(` */`);
  lines.push(`const crudGenerator = new CRUDGenerator(database);`);
  lines.push(``);

  // Generate routes
  lines.push(`// Generate CRUD routes`);
  lines.push(`const routes = crudGenerator.generate(${modelName}, {`);
  lines.push(`  basePath: '${basePath}',`);

  if (options.softDelete) {
    lines.push(`  enableSoftDelete: true,`);
  }

  if (options.pagination !== false) {
    lines.push(`  enablePagination: true,`);
    lines.push(`  defaultPageSize: 20,`);
    lines.push(`  maxPageSize: 100,`);
  }

  if (options.filtering !== false) {
    lines.push(`  enableFiltering: true,`);
  }

  if (options.sorting !== false) {
    lines.push(`  enableSorting: true,`);
  }

  if (options.search) {
    lines.push(`  enableSearch: true,`);
    lines.push(`  searchFields: [], // TODO: Add fields to search on`);
  }

  if (options.relationships) {
    lines.push(`  enableRelationships: true,`);
  }

  lines.push(`});`);
  lines.push(``);

  // Export route handlers
  lines.push(`// Export route handlers`);
  lines.push(`// List all ${modelName}s - GET ${basePath}`);
  lines.push(
    `export const GET = routes.find(r => r.method === 'GET' && r.path === '${basePath}')?.handler;`
  );
  lines.push(``);

  lines.push(`// Create ${modelName} - POST ${basePath}`);
  lines.push(`export const POST = routes.find(r => r.method === 'POST')?.handler;`);
  lines.push(``);

  lines.push(`/**`);
  lines.push(` * Individual ${modelName} operations`);
  lines.push(` * `);
  lines.push(` * Create a file at: src/routes${basePath}/[id].ts`);
  lines.push(` * with the following exports:`);
  lines.push(` * `);
  lines.push(` * // Get ${modelName} by ID - GET ${basePath}/:id`);
  lines.push(
    ` * export const GET = routes.find(r => r.method === 'GET' && r.path.includes(':id'))?.handler;`
  );
  lines.push(` * `);
  lines.push(` * // Update ${modelName} (full) - PUT ${basePath}/:id`);
  lines.push(` * export const PUT = routes.find(r => r.method === 'PUT')?.handler;`);
  lines.push(` * `);
  lines.push(` * // Update ${modelName} (partial) - PATCH ${basePath}/:id`);
  lines.push(` * export const PATCH = routes.find(r => r.method === 'PATCH')?.handler;`);
  lines.push(` * `);
  lines.push(` * // Delete ${modelName} - DELETE ${basePath}/:id`);
  lines.push(` * export const DELETE = routes.find(r => r.method === 'DELETE')?.handler;`);
  lines.push(` */`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Generate individual resource route file content
 */
function generateIndividualRouteContent(modelName: string, options: GenerateCRUDOptions): string {
  const basePath = options.basePath || `/${modelName.toLowerCase()}s`;
  const lines: string[] = [];

  // Imports
  lines.push(`import type { RequestContext, NextFunction } from '@web-loom/api-core';`);
  lines.push(`import { CRUDGenerator } from '@web-loom/api-generator-crud';`);
  lines.push(`import { ${modelName} } from '../../models/${modelName.toLowerCase()}.js';`);
  lines.push(
    `import { database } from '../../database.js'; // You'll need to export your database adapter`
  );
  lines.push(``);

  // Create CRUD generator instance
  lines.push(`/**`);
  lines.push(` * Individual ${modelName} operations`);
  lines.push(` * `);
  lines.push(` * Generated by Web Loom CLI`);
  lines.push(` */`);
  lines.push(`const crudGenerator = new CRUDGenerator(database);`);
  lines.push(``);

  // Generate routes
  lines.push(`// Generate CRUD routes`);
  lines.push(`const routes = crudGenerator.generate(${modelName}, {`);
  lines.push(`  basePath: '${basePath}',`);

  if (options.softDelete) {
    lines.push(`  enableSoftDelete: true,`);
  }

  if (options.pagination !== false) {
    lines.push(`  enablePagination: true,`);
    lines.push(`  defaultPageSize: 20,`);
    lines.push(`  maxPageSize: 100,`);
  }

  if (options.filtering !== false) {
    lines.push(`  enableFiltering: true,`);
  }

  if (options.sorting !== false) {
    lines.push(`  enableSorting: true,`);
  }

  if (options.search) {
    lines.push(`  enableSearch: true,`);
    lines.push(`  searchFields: [], // TODO: Add fields to search on`);
  }

  if (options.relationships) {
    lines.push(`  enableRelationships: true,`);
  }

  lines.push(`});`);
  lines.push(``);

  // Export route handlers for individual resource
  lines.push(`// Get ${modelName} by ID - GET ${basePath}/:id`);
  lines.push(
    `export const GET = routes.find(r => r.method === 'GET' && r.path.includes(':id'))?.handler;`
  );
  lines.push(``);

  lines.push(`// Update ${modelName} (full) - PUT ${basePath}/:id`);
  lines.push(`export const PUT = routes.find(r => r.method === 'PUT')?.handler;`);
  lines.push(``);

  lines.push(`// Update ${modelName} (partial) - PATCH ${basePath}/:id`);
  lines.push(`export const PATCH = routes.find(r => r.method === 'PATCH')?.handler;`);
  lines.push(``);

  lines.push(`// Delete ${modelName} - DELETE ${basePath}/:id`);
  lines.push(`export const DELETE = routes.find(r => r.method === 'DELETE')?.handler;`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Get route file paths
 */
function getRouteFilePaths(
  basePath: string,
  outputDir?: string
): { collectionPath: string; individualPath: string } {
  const routeDir = basePath.replace(/^\//, '').replace(/\//g, path.sep);

  if (outputDir) {
    return {
      collectionPath: path.join(outputDir, routeDir, 'index.ts'),
      individualPath: path.join(outputDir, routeDir, '[id].ts'),
    };
  }

  // Default to src/routes directory
  const baseDir = path.join(process.cwd(), 'src', 'routes');
  return {
    collectionPath: path.join(baseDir, routeDir, 'index.ts'),
    individualPath: path.join(baseDir, routeDir, '[id].ts'),
  };
}

/**
 * Check if model file exists
 */
async function checkModelExists(modelName: string): Promise<boolean> {
  const modelPath = path.join(process.cwd(), 'src', 'models', `${modelName.toLowerCase()}.ts`);

  try {
    await fs.access(modelPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate CRUD command handler
 */
async function generateCRUDCommand(modelName: string, options: GenerateCRUDOptions): Promise<void> {
  try {
    // Validate model name
    if (!modelName || !/^[A-Z][a-zA-Z0-9]*$/.test(modelName)) {
      throw new CLIError(
        'Model name must start with an uppercase letter and contain only alphanumeric characters'
      );
    }

    info(`Generating CRUD routes for: ${modelName}...\n`);

    // Check if model exists
    const modelExists = await checkModelExists(modelName);
    if (!modelExists) {
      logError(`Model file not found: src/models/${modelName.toLowerCase()}.ts`);
      info(`\nRun: webloom generate model ${modelName}`);
      throw new CLIError('Model not found');
    }

    // Determine base path
    const basePath = options.basePath || `/${modelName.toLowerCase()}s`;

    // Generate route content
    const collectionContent = generateCRUDRouteContent(modelName, options);
    const individualContent = generateIndividualRouteContent(modelName, options);

    // Get output paths
    const { collectionPath, individualPath } = getRouteFilePaths(basePath, options.output);

    // Ensure directories exist
    await fs.mkdir(path.dirname(collectionPath), { recursive: true });
    await fs.mkdir(path.dirname(individualPath), { recursive: true });

    // Check if files already exist
    try {
      await fs.access(collectionPath);
      throw new CLIError(
        `Route file already exists: ${collectionPath}\nUse --force to overwrite (not implemented yet)`
      );
    } catch (err: unknown) {
      if (err && typeof err === 'object' && 'code' in err && err.code !== 'ENOENT') {
        throw err;
      }
    }

    // Write files
    await fs.writeFile(collectionPath, collectionContent);
    await fs.writeFile(individualPath, individualContent);

    success(`\nCRUD routes generated successfully!`);
    info(`  Collection: ${collectionPath}`);
    info(`  Individual: ${individualPath}`);

    info(`\nGenerated endpoints:`);
    info(`  GET    ${basePath}           - List all ${modelName}s`);
    info(`  POST   ${basePath}           - Create ${modelName}`);
    info(`  GET    ${basePath}/:id       - Get ${modelName} by ID`);
    info(`  PUT    ${basePath}/:id       - Update ${modelName} (full)`);
    info(`  PATCH  ${basePath}/:id       - Update ${modelName} (partial)`);
    info(`  DELETE ${basePath}/:id       - Delete ${modelName}`);

    info(`\nNext steps:`);
    info(`  1. Create src/database.ts and export your database adapter`);
    info(`  2. Review and customize the generated routes`);
    info(`  3. Run: webloom dev`);
  } catch (err) {
    if (err instanceof CLIError) {
      throw err;
    }
    logError(`Failed to generate CRUD routes: ${err}`);
    throw new CLIError('CRUD generation failed');
  }
}

/**
 * Create generate CRUD command
 */
export function createGenerateCRUDCommand(): Command {
  return new Command('crud')
    .description('Generate CRUD routes for a model')
    .argument('<model>', 'Model name (PascalCase)')
    .option('-o, --output <dir>', 'Output directory (default: src/routes)')
    .option('-p, --base-path <path>', 'Base path for routes (default: /models)')
    .option('--soft-delete', 'Enable soft delete support')
    .option('--no-pagination', 'Disable pagination')
    .option('--no-filtering', 'Disable filtering')
    .option('--no-sorting', 'Disable sorting')
    .option('--search', 'Enable search functionality')
    .option('--relationships', 'Enable relationship loading')
    .action(wrapCommand(generateCRUDCommand));
}
