/**
 * OpenAPI Generator
 * 
 * Generates OpenAPI 3.1 specifications from model and route definitions
 */

import type { RouteDefinition } from '@web-loom/api-core';
import type { HTTPMethod } from '@web-loom/api-shared';
import type {
  OpenAPISpec,
  OpenAPIGeneratorOptions,
  OpenAPISchema,
  OpenAPIPathItem,
  OpenAPIOperation,
  OpenAPIParameter,
  OpenAPIRequestBody,
  OpenAPIResponse,
  OpenAPIComponents,
  OpenAPIInfo,
  OpenAPIServer,
  OpenAPISecurityScheme,
  OpenAPISecurityRequirement,
  OpenAPITag,
  OpenAPIContact,
  OpenAPILicense,
  OpenAPIExternalDocs,
} from './types';
import { fieldToSchema, generateExampleValue, type FieldDefinition } from './schema-mapper';

/**
 * Model definition for OpenAPI generation
 */
export interface ModelDefinition {
  name: string;
  tableName?: string;
  fields: FieldDefinition[];
  relationships?: Array<{
    type: 'hasOne' | 'hasMany' | 'belongsTo' | 'manyToMany';
    model: string;
    foreignKey?: string;
    localKey?: string;
    through?: string;
    as?: string;
  }>;
  options?: {
    timestamps?: boolean;
    softDelete?: boolean;
    optimisticLocking?: boolean;
    crud?: boolean;
    permissions?: Record<string, string[]>;
  };
  metadata?: {
    description?: string;
    tags?: string[];
    deprecated?: boolean;
    version?: string;
    examples?: Record<string, unknown>[];
  };
}

/**
 * OpenAPI Generator Class
 * 
 * Generates OpenAPI 3.1 specifications from Web Loom models and routes
 */
export class OpenAPIGenerator {
  private models: Map<string, ModelDefinition> = new Map();
  private routes: RouteDefinition[] = [];
  private options: {
    title: string;
    version: string;
    description: string;
    servers: OpenAPIServer[];
    contact?: OpenAPIContact;
    license?: OpenAPILicense;
    securitySchemes: Record<string, OpenAPISecurityScheme>;
    security: OpenAPISecurityRequirement[];
    tags: OpenAPITag[];
    externalDocs?: OpenAPIExternalDocs;
    includeExamples: boolean;
    includeDeprecated: boolean;
  };

  constructor(options: OpenAPIGeneratorOptions = {}) {
    this.options = {
      title: options.title || 'Web Loom API',
      version: options.version || '1.0.0',
      description: options.description || 'API generated by Web Loom Framework',
      servers: options.servers || [{ url: 'http://localhost:3000' }],
      securitySchemes: options.securitySchemes || {},
      security: options.security || [],
      tags: options.tags || [],
      includeExamples: options.includeExamples ?? true,
      includeDeprecated: options.includeDeprecated ?? true,
    };

    // Only assign optional properties if they exist
    if (options.contact) {
      this.options.contact = options.contact;
    }

    if (options.license) {
      this.options.license = options.license;
    }

    if (options.externalDocs) {
      this.options.externalDocs = options.externalDocs;
    }
  }

  /**
   * Register a model definition
   */
  registerModel(model: ModelDefinition): void {
    this.models.set(model.name, model);
  }

  /**
   * Register multiple model definitions
   */
  registerModels(models: ModelDefinition[]): void {
    for (const model of models) {
      this.registerModel(model);
    }
  }

  /**
   * Register a route definition
   */
  registerRoute(route: RouteDefinition): void {
    this.routes.push(route);
  }

  /**
   * Register multiple route definitions
   */
  registerRoutes(routes: RouteDefinition[]): void {
    this.routes.push(...routes);
  }

  /**
   * Generate OpenAPI specification
   */
  generate(): OpenAPISpec {
    const info: OpenAPIInfo = {
      title: this.options.title,
      version: this.options.version,
      description: this.options.description,
    };

    if (this.options.contact) {
      info.contact = this.options.contact;
    }

    if (this.options.license) {
      info.license = this.options.license;
    }

    const spec: OpenAPISpec = {
      openapi: '3.1.0',
      info,
      servers: this.options.servers,
      paths: this.generatePaths(),
      components: this.generateComponents(),
    };

    // Add security if configured
    if (this.options.security.length > 0) {
      spec.security = this.options.security;
    }

    // Add tags if configured
    if (this.options.tags.length > 0) {
      spec.tags = this.options.tags;
    }

    // Add external docs if configured
    if (this.options.externalDocs) {
      spec.externalDocs = this.options.externalDocs;
    }

    return spec;
  }

  /**
   * Generate paths from routes
   */
  private generatePaths(): Record<string, OpenAPIPathItem> {
    const paths: Record<string, OpenAPIPathItem> = {};

    for (const route of this.routes) {
      // Skip deprecated routes if not included
      if (route.metadata?.deprecated && !this.options.includeDeprecated) {
        continue;
      }

      // Convert :param to {param} format for OpenAPI
      const path = route.path.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');

      // Initialize path item if not exists
      if (!paths[path]) {
        paths[path] = {};
      }

      // Add operation for this method
      const method = route.method.toLowerCase() as Lowercase<HTTPMethod>;
      paths[path][method] = this.generateOperation(route);
    }

    return paths;
  }

  /**
   * Generate operation from route
   */
  private generateOperation(route: RouteDefinition): OpenAPIOperation {
    const operation: OpenAPIOperation = {
      summary: route.metadata?.description || `${route.method} ${route.path}`,
      operationId: this.generateOperationId(route),
      parameters: this.generateParameters(route),
      responses: this.generateResponses(route),
    };

    // Add optional fields only if they exist
    if (route.metadata?.description) {
      operation.description = route.metadata.description;
    }

    if (route.metadata?.tags && route.metadata.tags.length > 0) {
      operation.tags = route.metadata.tags;
    }

    if (route.metadata?.deprecated) {
      operation.deprecated = true;
    }

    // Add request body for POST, PUT, PATCH
    if (['POST', 'PUT', 'PATCH'].includes(route.method)) {
      const requestBody = this.generateRequestBody(route);
      if (requestBody) {
        operation.requestBody = requestBody;
      }
    }

    // Add security requirements
    if (route.auth?.required) {
      operation.security = this.generateSecurityRequirements(route);
    }

    return operation;
  }

  /**
   * Generate operation ID from route
   */
  private generateOperationId(route: RouteDefinition): string {
    const method = route.method.toLowerCase();
    const pathParts = route.path
      .split('/')
      .filter(Boolean)
      .map(part => part.replace(/[^a-zA-Z0-9]/g, ''));
    
    return `${method}${pathParts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('')}`;
  }

  /**
   * Generate parameters from route
   */
  private generateParameters(route: RouteDefinition): OpenAPIParameter[] {
    const parameters: OpenAPIParameter[] = [];

    // Extract path parameters
    const pathParams = route.path.match(/:([a-zA-Z0-9_]+)/g);
    if (pathParams) {
      for (const param of pathParams) {
        const paramName = param.substring(1);
        parameters.push({
          name: paramName,
          in: 'path',
          required: true,
          schema: { type: 'string' },
          description: `${paramName} parameter`,
        });
      }
    }

    // Add query parameters for GET requests
    if (route.method === 'GET' && route.validation?.query) {
      // TODO: Parse query validation schema
      // For now, add common pagination parameters
      parameters.push(
        {
          name: 'page',
          in: 'query',
          required: false,
          schema: { type: 'integer', minimum: 1, default: 1 },
          description: 'Page number for pagination',
        },
        {
          name: 'limit',
          in: 'query',
          required: false,
          schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 },
          description: 'Number of items per page',
        }
      );
    }

    return parameters;
  }

  /**
   * Generate request body from route
   */
  private generateRequestBody(route: RouteDefinition): OpenAPIRequestBody | undefined {
    // Try to infer schema from route path (e.g., /users -> User model)
    const modelName = this.inferModelFromPath(route.path);
    const model = modelName ? this.models.get(modelName) : undefined;

    let schema: OpenAPISchema;
    if (model) {
      schema = { $ref: `#/components/schemas/${model.name}` };
    } else {
      schema = { type: 'object' };
    }

    return {
      description: 'Request body',
      required: true,
      content: {
        'application/json': {
          schema,
        },
      },
    };
  }

  /**
   * Generate responses from route
   */
  private generateResponses(route: RouteDefinition): Record<string, OpenAPIResponse> {
    const responses: Record<string, OpenAPIResponse> = {};

    // Use metadata responses if available
    if (route.metadata?.responses) {
      for (const response of route.metadata.responses) {
        const responseObj: OpenAPIResponse = {
          description: response.description,
        };

        if (response.schema) {
          responseObj.content = {
            'application/json': {
              schema: response.schema as OpenAPISchema,
            },
          };
        }

        responses[response.status.toString()] = responseObj;
      }
      return responses;
    }

    // Generate default responses based on method
    const modelName = this.inferModelFromPath(route.path);
    const model = modelName ? this.models.get(modelName) : undefined;

    switch (route.method) {
      case 'GET':
        if (route.path.includes(':')) {
          // Single resource
          const getResponse: OpenAPIResponse = {
            description: 'Successful response',
          };
          if (model) {
            getResponse.content = {
              'application/json': {
                schema: { $ref: `#/components/schemas/${model.name}` },
              },
            };
          }
          responses['200'] = getResponse;
        } else {
          // List of resources
          const listResponse: OpenAPIResponse = {
            description: 'Successful response',
          };
          if (model) {
            listResponse.content = {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    data: {
                      type: 'array',
                      items: { $ref: `#/components/schemas/${model.name}` },
                    },
                    pagination: {
                      type: 'object',
                      properties: {
                        page: { type: 'integer' },
                        limit: { type: 'integer' },
                        total: { type: 'integer' },
                        totalPages: { type: 'integer' },
                      },
                    },
                  },
                },
              },
            };
          }
          responses['200'] = listResponse;
        }
        responses['404'] = {
          description: 'Resource not found',
        };
        break;

      case 'POST':
        const postResponse: OpenAPIResponse = {
          description: 'Resource created successfully',
        };
        if (model) {
          postResponse.content = {
            'application/json': {
              schema: { $ref: `#/components/schemas/${model.name}` },
            },
          };
        }
        responses['201'] = postResponse;
        responses['400'] = {
          description: 'Invalid request body',
        };
        break;

      case 'PUT':
      case 'PATCH':
        const updateResponse: OpenAPIResponse = {
          description: 'Resource updated successfully',
        };
        if (model) {
          updateResponse.content = {
            'application/json': {
              schema: { $ref: `#/components/schemas/${model.name}` },
            },
          };
        }
        responses['200'] = updateResponse;
        responses['400'] = {
          description: 'Invalid request body',
        };
        responses['404'] = {
          description: 'Resource not found',
        };
        break;

      case 'DELETE':
        responses['200'] = {
          description: 'Resource deleted successfully',
        };
        responses['404'] = {
          description: 'Resource not found',
        };
        break;

      default:
        responses['200'] = {
          description: 'Successful response',
        };
    }

    // Add common error responses
    responses['401'] = {
      description: 'Unauthorized',
    };
    responses['500'] = {
      description: 'Internal server error',
    };

    return responses;
  }

  /**
   * Generate security requirements from route
   */
  private generateSecurityRequirements(route: RouteDefinition): Array<Record<string, string[]>> {
    const requirements: Array<Record<string, string[]>> = [];

    // If route has specific scopes, use them
    if (route.auth?.scopes && route.auth.scopes.length > 0) {
      // Assume first security scheme
      const schemeName = Object.keys(this.options.securitySchemes)[0];
      if (schemeName) {
        requirements.push({ [schemeName]: route.auth.scopes });
      }
    } else if (route.auth?.required) {
      // Use empty scopes for required auth
      const schemeName = Object.keys(this.options.securitySchemes)[0];
      if (schemeName) {
        requirements.push({ [schemeName]: [] });
      }
    }

    return requirements;
  }

  /**
   * Generate components (schemas, security schemes, etc.)
   */
  private generateComponents(): OpenAPIComponents {
    const components: OpenAPIComponents = {
      schemas: this.generateSchemas(),
    };

    // Add security schemes if configured
    if (Object.keys(this.options.securitySchemes).length > 0) {
      components.securitySchemes = this.options.securitySchemes;
    }

    return components;
  }

  /**
   * Generate schemas from models
   */
  private generateSchemas(): Record<string, OpenAPISchema> {
    const schemas: Record<string, OpenAPISchema> = {};

    for (const [name, model] of this.models) {
      schemas[name] = this.modelToSchema(model);
    }

    return schemas;
  }

  /**
   * Convert model definition to OpenAPI schema
   */
  private modelToSchema(model: ModelDefinition): OpenAPISchema {
    const properties: Record<string, OpenAPISchema> = {};
    const required: string[] = [];

    for (const field of model.fields) {
      properties[field.name] = fieldToSchema(field);

      // Add to required array if field is required
      if (field.validation?.required) {
        required.push(field.name);
      }
    }

    const schema: OpenAPISchema = {
      type: 'object',
      title: model.name,
      properties,
    };

    // Add optional fields only if they exist
    if (model.metadata?.description) {
      schema.description = model.metadata.description;
    }

    if (required.length > 0) {
      schema.required = required;
    }

    // Add example if enabled
    if (this.options.includeExamples && model.metadata?.examples && model.metadata.examples.length > 0) {
      schema.example = model.metadata.examples[0];
    } else if (this.options.includeExamples) {
      schema.example = this.generateModelExample(model);
    }

    return schema;
  }

  /**
   * Generate example object for a model
   */
  private generateModelExample(model: ModelDefinition): Record<string, unknown> {
    const example: Record<string, unknown> = {};

    for (const field of model.fields) {
      if (!field.computed) {
        example[field.name] = generateExampleValue(field.type, field.name);
      }
    }

    return example;
  }

  /**
   * Infer model name from route path
   * Examples:
   *   /users -> User
   *   /posts/:id -> Post
   *   /api/v1/products -> Product
   */
  private inferModelFromPath(path: string): string | null {
    const parts = path.split('/').filter(Boolean);
    
    // Find the first part that doesn't start with : and isn't 'api' or version
    for (const part of parts) {
      if (!part.startsWith(':') && !part.match(/^(api|v\d+)$/i)) {
        // Convert plural to singular and capitalize
        const singular = part.endsWith('s') ? part.slice(0, -1) : part;
        return singular.charAt(0).toUpperCase() + singular.slice(1);
      }
    }

    return null;
  }

  /**
   * Export specification as JSON string
   */
  toJSON(pretty = true): string {
    const spec = this.generate();
    return JSON.stringify(spec, null, pretty ? 2 : 0);
  }

  /**
   * Export specification as YAML string
   */
  toYAML(): string {
    // Simple YAML conversion (for production, use a proper YAML library)
    const spec = this.generate();
    return this.objectToYAML(spec);
  }

  /**
   * Simple object to YAML converter
   */
  private objectToYAML(obj: unknown, indent = 0): string {
    const spaces = '  '.repeat(indent);
    
    if (obj === null || obj === undefined) {
      return 'null';
    }
    
    if (typeof obj === 'string') {
      return obj.includes('\n') ? `|\n${spaces}  ${obj.replace(/\n/g, `\n${spaces}  `)}` : obj;
    }
    
    if (typeof obj === 'number' || typeof obj === 'boolean') {
      return String(obj);
    }
    
    if (Array.isArray(obj)) {
      if (obj.length === 0) return '[]';
      return '\n' + obj.map(item => `${spaces}- ${this.objectToYAML(item, indent + 1)}`).join('\n');
    }
    
    if (typeof obj === 'object') {
      const entries = Object.entries(obj);
      if (entries.length === 0) return '{}';
      
      return '\n' + entries
        .map(([key, value]) => {
          const yamlValue = this.objectToYAML(value, indent + 1);
          return `${spaces}${key}:${yamlValue.startsWith('\n') ? yamlValue : ' ' + yamlValue}`;
        })
        .join('\n');
    }
    
    return String(obj);
  }
}
